---
engines:
 eslint:
 - src/serviceWorker.js
 - src/App.test.js
 enabled: true
exclude_paths:
- build/**
- coverage/**
- docs/**
- jsdoc/**
- templates/**
- tests/bench/**
- test-config/**
- tests/fixtures/**
- tests/performance/**
- tmp/**
- next.config.js